#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
use Minicli\Curly\Client;
use Minicli\Stencil;

$ignoreUsers = getenv('CONTRIB_IGNORE') ?: 'github-actions[bot],renovate-bot,dependabot';
$app = new App([
    'app_path' => __DIR__ . '/app/Command',
    'repository' => getenv('CONTRIB_REPOSITORY') ?: null,
    'output_file' => getenv('CONTRIB_OUTPUT_FILE') ?: 'CONTRIBUTORS.md',
    'template' => getenv('CONTRIB_TEMPLATE') ?: 'contributors',
    'ignore_users' => explode(',', $ignoreUsers)
]);

$app->registerCommand('update-contributors', function () use ($app) {

    if (!$app->config->has('repository')) {
        $app->getPrinter()->error("Missing CONTRIB_REPOSITORY environment variable.");
        return 1;
    }

    $app->getPrinter()->info('Fetching top contributors...');

    $client = new Client();
    $response = $client->get(
        "https://api.github.com/repos/" . $app->config->repository . "/contributors",
        ['Accept: application/vnd.github.v3+json', 'User-Agent: Curly']
    );

    if ($response['code'] != 200) {
        $app->getPrinter()->error("an error occurred: " . $response['code']);
        return 1;
    }

    $stencil = new Stencil(__DIR__);

    $content = "";
    foreach (json_decode($response['body']) as $item) {
        if (!in_array($item->login, $app->config->ignore_users)) {
            $content .= "- [$item->login]($item->html_url)\n";
        }
    }

    $output = $stencil->applyTemplate($app->config->template, [
        'repo' => $app->config->repository,
        'content' => $content,
        'updated' => (new DateTimeImmutable())->format(DateTimeInterface::RFC822)
    ]);

    try {
        $contrib_file = fopen($app->config->output_file, 'w+');
        fwrite($contrib_file, $output);
        fclose($contrib_file);
    } catch (Exception $exception) {
        $app->getPrinter()->error("An error occurred while trying to save the contrib file.");
        return 1;
    }

    $app->getPrinter()->success("Finished updating contrib file.");
    return 0;
});

$app->runCommand($argv);
